{
    'name': 'MLM Affiliate Referral',
    'version': '18.0.4.0.0',
    'category': 'Website/eCommerce',
    'summary': 'Multi-level affiliate referral commissions for Odoo 18 eCommerce',
    'author': 'Custom Development',
    'depends': [
        'website_sale',
        'sale_management',
        'account',
        'portal',
        'mail',
        'auth_signup',
        'base_setup',
    ],
    'data': [
        'security/mlm_security.xml',
        'security/ir.model.access.csv',
        'data/sequence_data.xml',
        'data/mail_templates.xml',
        'data/cron_data.xml',
        'views/mlm_level_rate_views.xml',
        'views/mlm_affiliate_tier_views.xml',
        'views/mlm_leaderboard_views.xml',
        'views/product_commission_rule_views.xml',
        'views/product_category_views.xml',
        'views/res_partner_views.xml',
        'views/mlm_commission_views.xml',
        'views/product_template_views.xml',
        'views/portal_affiliate_views.xml',
        'views/website_sale_wallet.xml',
        'views/website_templates.xml',
        'views/mlm_settings_views.xml',
        'views/menus.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'mlm_affiliate/static/src/js/referral_tracker.js',
            'mlm_affiliate/static/src/js/affiliate_share.js',
            'mlm_affiliate/static/src/js/wallet_cart.js',
        ],
    },
    'external_dependencies': {
        'python': [],   # qrcode is optional — QR panel silently hidden if not installed
    },
    'pre_init_hook': 'pre_init_hook',
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
