from . import res_partner
from . import res_config_settings
from . import mlm_level_rate
from . import mlm_affiliate_tier
from . import mlm_commission
from . import mlm_link_builder
from . import product_commission_rule
from . import product_template
from . import sale_order
from . import account_move
